apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  source:
    repoURL: https://github.com/dm0275/argo-gitops.git
    path: applications/1-directory
    targetRevision: main
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s